### PR TITLE
features: add Wasm-GC and Chrome's current support

### PR DESCRIPTION
**Pull request by kevmoo**
See also: https://github.com/GoogleChromeLabs/wasm-feature-detect/issues/60

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @sbc100

**Comment by chicoxyzzy** [comment]
I believe that Firefox has GC support under flag too

**Comment by sbc100** [comment]
@tlively

**Comment by eqrion** [comment]
We have a GC implementation, but it doesn't have full support and it's targeting an older milestone from V8. It's probably not worth mentioning that until we're updated. We're currently focusing on perf.

**Comment by bashor** [comment]
+1, for adding Firefox to the list. 
We (Kotlin/Wasm) tried it, and I'd say it's already usable, at least, we passed almost all our compiler tests using a nightly build.

Speaking about fullness -- we noticed only one thing, modulo bugs:), SpiderMonkey uses old and not all instructions for casts and br+casts.

**Comment by eqrion** [comment]
> +1, for adding Firefox to the list. We (Kotlin/Wasm) tried it, and I'd say it's already usable, at least, we passed almost all our compiler tests using a nightly build.
> 
> Speaking about fullness -- we noticed only one thing, modulo bugs:), SpiderMonkey uses old and not all instructions for casts and br+casts.

Oh, glad to hear that. And yeah, casting is the biggest area where we're behind. It's also been a recent area of churn in the spec, which is why we're temporarily focused on perf rather than updating to latest. We will probably update the casting implementation later in February.

Also, if the bugs are in SM and you have free time, we'd appreciate a bug report [1] and I can look into it.

[1] https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=JavaScript%3A+WebAssembly

**Comment by bashor** [comment]
@eqrion I reported a few bugs last week. I'll drop you a message somewhere.

**Comment by kevmoo** [comment]
Just bump this w/ the latest feature detect version. GC enabled is now displayed!

**Comment by kevmoo** [comment]
image

enabled wasm-gc in firefox nightly

image


🤷

**Comment by kevmoo** [comment]
We still waiting on Firefox data in the column? @eqrion @tlively

**Comment by tlively** [comment]
I'd be happy to iterate on the firefox listing separately. This LGTM but I don't have commit privileges in this repo @dschuff.

**Review by chicoxyzzy — APPROVED** [review]

**Comment by dschuff** [comment]
Thanks!

**Comment by kevmoo** [comment]
Firefox nightly (with flags) 👍 

image

**Pull request merged**
