### PR TITLE
Aded SVG link to home page

### PR DESCRIPTION
**Pull request by shinmem58**
As discussed in issue #143  I added to the SVG a link to the home page.
I added href and xlink:href for backwards compatibility and for safari.

For some reason when I compare the code it shows that I rewrote the SVG when a really added lines 14, 36.

### CODE REVIEW

**Comment by binji** [comment]
I tried loading this SVG in Chrome and it gives the following error:

```
This page contains the following errors:
error on line 14 at column 29: Namespace prefix xlink for href on a is not defined
Below is a rendering of the page up to the first error.
```

**Comment by shinmem58** [comment]
I fixed the problem.
Should I make a new pull rquest ?

**Comment by RReverser** [comment]
What was this change about? It's hard to tell with all the indentation changes.

**Comment by RReverser** [comment]
Ah I see now on the original issue. However, I'd prefer to add a link in HTML instead - it should be as easy as changing `div` to `a`.

**Comment by RReverser** [comment]
I've tried to use this PR, but it doesn't work because SVG is used in `background-image` context where it can't have links. I'll switch `div` -> `a` as described above instead.

**Pull request closed without merging**
