### PR TITLE
Add GraalWasm to "Feature Extensions" page.

### PR DESCRIPTION
**Pull request by fniephaus**
(Disclaimer: I'm on the [GraalVM](https://www.graalvm.org/) team that maintains GraalWasm).

This PR adds GraalWasm to the [Feature Extensions page](https://webassembly.org/features/). GraalWasm is an [open-source](https://github.com/oracle/graal/tree/master/wasm) WebAssembly runtime written in Java using our [Truffle framework](https://www.graalvm.org/latest/graalvm-as-a-platform/language-implementation-framework/). We introduced [it in 2019](https://medium.com/graalvm/announcing-graalwasm-a-webassembly-engine-in-graalvm-25cd0400a7f2) and plan to declare it as stable in the upcoming 24.1.0 release on September 17, 2024.

Note that https://graalvm.org/webassembly will become available in the next couple of days, we are still working on it.

I thought I open this PR now because it seems that the Feature Extensions page may need a little tweaking. With the additional GraalWasm entry, the table starts to become wider than the content box, causing an awkward horizontal scrollbar (see below). I'm happy to incorporate any fixes or improvements for this.

image

### CODE REVIEW

**Comment by tomayac** [comment]
Thanks for adding this! As you're at it, maybe group all pure Wasm engines together, that is, move Node.js and Deno after the browsers, and then come all the Wasm engines. 

I'll be working on the site soon™, so for now I think it's fine if the table requires scrolling and maybe doesn't look perfect.

**Comment by fniephaus** [comment]
> As you're at it, maybe group all pure Wasm engines together, that is, move Node.js and Deno after the browsers, and then come all the Wasm engines.

Sure, happy to do that. It's just that GraalWasm can not just be used as pure Wasm engine, but also in conjunction with [GraalJS (our JavaScript runtime) and even in our GraalVM Node.js runtime](https://github.com/oracle/graaljs). So I'd argue it's somewhere in between Node.js/Deno and the pure Wasm engines. Should I put it in between? What do you think?

> I'll be working on the site soon™, so for now I think it's fine if the table requires scrolling and maybe doesn't look perfect.

Ok great, thank you!

**Comment by tomayac** [comment]
> > As you're at it, maybe group all pure Wasm engines together, that is, move Node.js and Deno after the browsers, and then come all the Wasm engines.
> 
> Sure, happy to do that. It's just that GraalWasm can not just be used as pure Wasm engine, but also in conjunction with [GraalJS (our JavaScript runtime) and even in our GraalVM Node.js runtime](https://github.com/oracle/graaljs). So I'd argue it's somewhere in between Node.js/Deno and the pure Wasm engines. Should I put it in between? What do you think?

SGTM, thanks!

**Comment by fniephaus** [comment]
@tomayac I have re-ordered the engines as discussed (see updated screenshot in the PR description).

I've also changed the link for GraalWasm, so that this can be merged now. I can open a follow-up PR to adjust the link to the new landing page for GraalWasm when it's ready.

**Comment by tomayac** [comment]
Thank you very much!

**Comment by fniephaus** [comment]
Thanks for accepting the PR. :)

**Pull request merged**
