### PR TITLE
Update relaxed SIMD status for Chrome

### PR DESCRIPTION
**Pull request by ngzhian**
@dtig I think this is the right flag?

### CODE REVIEW

**Comment by RReverser** [comment]
So... is it?

**Comment by ngzhian** [comment]
Probably not, enable-experimental-webassembly-features implies --wasm-staging, but we need --wasm-experimental-relaxed-simd. I think there might not be a Chrome flag for this yet? @dtig

**Comment by dtig** [comment]
@ngzhian is right, that this needs to be in wasm-staging, both of these should happen soon though - there's a pending instruction to moving to staging, and I'll be adding a chrome flag for ease of experimentation. So while this PR isn't quite right for now, but it will be applicable soon. Perhaps leave it open and I can merge with the Chrome version where it's supported flagged?

**Comment by dschuff** [comment]
so there's a v8 flag `--wasm-experimental-relaxed-simd`? In that case we could just do what we do for memory64 and extended-const.

**Comment by dtig** [comment]
We do have a chrome flag now (landed in Nov, but I forgot to update this thread). The flag is WebAssemblyRelaxedSimd, and is available from Chrome 110 onwards.

**Comment by dschuff** [comment]
the format for flags in `chrome://flags` in this file is e.g. `chrome://flags/#enable-webassembly-relaxed-simd`

**Comment by dschuff** [comment]
Interestingly, this page's general format doesn't easily support listing both a version and a flag, since the flag icon replaces the version number in the box.

**Comment by RReverser** [comment]
> doesn't easily support listing both a version and a flag, since the flag icon replaces the version number in the box.

Yeah the idea is that if something is under the flag, then people will want to use a flag on a bleeding-edge version of the browser to stay up-to-date with spec anyway, and if something is stable, then minimal version is useful.

**Review by chicoxyzzy — APPROVED** [review]

**Comment by dschuff** [comment]
I think this isn't "staged" yet, so the flag needs to be `chrome://flags/#enable-webassembly-relaxed-simd`

**Comment by chicoxyzzy** [comment]
On the website it says `Requires flag --js-flags=--experimental-wasm-relaxed-simd` already. Should we close this PR?

**Comment by dschuff** [comment]
Actually I think https://chromium-review.googlesource.com/c/v8/v8/+/4285497 means that as of Chrome 112, relaxed SIMD should be enabled with the flag in this PR (instead of its own flag). So (assuming that developers are using pre-stable versions of Chromium for testing pre-release wasm features as they should) maybe we should actually merge this.

**Comment by dschuff** [comment]
OK, I just checked and found several recent updates in Chrome and created https://github.com/WebAssembly/website/pull/328 to cover those, so I think we can actually close this.

**Comment by chicoxyzzy** [comment]
#328 has been merged

**Pull request closed without merging**
