### PR TITLE
Update status of SIMD on Safari

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Tail Calls are also available in Safari 16.4. Although 16.4 is still in beta.

**Comment by dschuff** [comment]
Oh, interesting, I didn't see it in https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
Is it on by default?

**Comment by dschuff** [comment]
(maybe @justinmichaud can clarify on whether Tail Calls are officially launched in Safari?)

**Comment by chicoxyzzy** [comment]
The `wasm-feature-detect` tests are passing for me since Safari TP 161 and also pass on 16.4 beta

[WebKit commit](https://github.com/WebKit/WebKit/commit/5ee0680f666939490e0bb03f07ba1ce6088609ec)

**Comment by chicoxyzzy** [comment]
Tail Calls were disabled in Safari TP 164 https://github.com/WebKit/WebKit/commit/3eb123c1f36f03ab8b1f521de8f01aaf541854c8

**Pull request merged**
