### PR TITLE
Remove the Wasm 1.0 banner

### PR DESCRIPTION
**Pull request by bvisness**
Per some CG meeting discussion :)

(This PR is a bit cheeky, and it may be better to instead update the contents of the banner to reflect what is currently shipped.)

### CODE REVIEW

**Comment by dschuff** [comment]
Generally LGTM, but maybe we should separate the dependence updates from the functional change :)

**Comment by chicoxyzzy** [comment]
@bvisness would you be open to revert changes in gemfile?

**Review by tomayac — APPROVED** [review]
I wasn't asked, but this change LGTM.

**Review by chicoxyzzy — APPROVED** [review]

**Comment by bvisness** [comment]
I'll revert the gemfile stuff, yeah.

**Comment by sunfishcode** [comment]
@bvisness Friendly ping; could you revert the gemfile changes here?

**Comment by sunfishcode** [comment]
Thanks!

**Pull request merged**
