### PR TITLE
Add a front page with all the tests

### PR DESCRIPTION
**Pull request by bnjbvr**
This adds a one-click front page for running all the tests (wast tests, pure JS tests and HTML tests) on the WebAssembly web site, so that one can just go there and test themselves for feature compliance of their current browser.

This depends on https://github.com/WebAssembly/spec/pull/419 being done first. The interesting commit (= the one that doesn't include built files) is https://github.com/WebAssembly/website/commit/2cb7584b9920aa6ca486e98a531c92847083748e. It adds the spec repository as a sub-module and includes a Makefile to easily regenerate tests (in an automated scenario, just a single make line would be needed).

Probably we'd need to add some explanations there first, and add some style rules to the generated content too. I've added a link to the test page from the front page, but maybe we could withdraw it, and re-add it later.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Now that #419 has been merged, this is not a work-in-progress anymore. I've updated the commits and regenerated the tests and one-click front page.

@dschuff, can you have a look please? Thanks!

**Comment by dschuff** [comment]
(sorry, I missed this in my inbox). It looks OK to me, but I'm not sure I have all the right context. Also @s3ththompson should look too.

**Comment by adanilo** [comment]
I've done a first-pass review, looks fine to me so far. Any chance the conflicts could be resolved?

**Comment by dschuff** [comment]
Presumably we'd want to also re-generate the tests to capture changes in the last year+. But also, we should make sure this is a thing people still want.

**Comment by adanilo** [comment]
Agreed, should we raise this at the next CG meeting?

**Comment by bnjbvr** [comment]
This has stalled for a while, and I'm not even sure this is something people want. It made sense at some point to be able to compare implementation progress. Now since everybody has the MVP, it's a bit unclear that it's useful, except maybe for tracking implementation progress on new proposals. Closing at the moment.

**Pull request closed without merging**
