### PR TITLE
Add zig to getting started

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by RReverser** [comment]
Thanks for your contribution! As you can see, the Travis has failed due to HTML mismatch - unfortunately, we currently commit all build artifacts, which means that you need to build website locally and update the PR. Could you please do that?

I think you also need to join WebAssembly CG, although I'm not sure how strict that requirement is for contributions. @binji ?

**Comment by RReverser** [comment]
Thanks for the update! Can you please join https://www.w3.org/community/webassembly/ as well?

**Comment by binji** [comment]
@RReverser For any significant changes, we're pretty strict. For small typo fixes, we usually don't require it. I guess the question is where this lands -- personally I'd say it could go either way.

**Comment by RReverser** [comment]
@binji Could / should we include some sort of check as part of the CI? Is it even possible? It would certainly make it easier to communicate this to folks and get it fixed sooner if it was automated.

**Comment by binji** [comment]
@RReverser yes, we have a check for this already in the spec repo, and we could add it here too. It requires a bit more than just joining the CG, however.

**Comment by RReverser** [comment]
Hmm isn't that what you said to do in https://github.com/WebAssembly/website/pull/120#issuecomment-639182961?

**Comment by binji** [comment]
Sorry, I mean the bot requires you to do more than just join the CG.

**Comment by RReverser** [comment]
Ah ok. Do you think you could integrate it here if you already know how it works?

**Comment by binji** [comment]
I didn't set it up originally, but now that it is already in the spec repo, I may be able to use the same thing here. I'll take a look. (here's the tool, in case you're curious https://github.com/w3c/ash-nazg/)

**Comment by RReverser** [comment]
@kubo39 Ping. I'd love to merge this, but can you please confirm that you joined the CG?

**Comment by kubo39** [comment]
@RReverser 
Sorry for late response. I'm unclear on whether I'm eligible to participate, I'm not employed by a W3C Member.
https://www.w3.org/participate/faq#individual

**Comment by RReverser** [comment]
Sigh. Thanks for checking it out.

@binji I suppose I can go with "this is a small change" here, but do you think we could take the website from under these restrictions? Is it technically under W3C umbrella?

Ideally I'd want contributors to feel free to send patches without a complicated process, if possible.

**Comment by binji** [comment]
@kubo39 You don't have to be employed by a W3C member, you can also join as an individual. But I understand if you don't want to do that.

@RReverser 
That reminds me: when we've discussed this before (w.r.t. projects like binaryen and wabt), we found that the main concern for w3c is the spec document, not the other artifacts (others please correct me if I'm misremembering). @ericprud is that correct?

**Comment by RReverser** [comment]
I'm going to take a risk and proceed here. Thanks again @kubo39!

**Pull request merged**
