### PR TITLE
Update Firefox version in the feature support table

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#WebAssembly

### CODE REVIEW

**Comment by lars-t-hansen** [comment]
Note SIMD is nightly-only at the moment, though the table says "Beta 79".

**Comment by chicoxyzzy** [comment]
@lars-t-hansen thank you for pointing out! fixed!

**Comment by RReverser** [comment]
Sorry I missed this one, merged #184 instead.

**Comment by chicoxyzzy** [comment]
@RReverser no problem! thanks!

**Pull request closed without merging**
