### PR TITLE
Safari 18.2 updates

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Safari 18.2 is still in beta, so let's wait until Sequoia 15.2 and iOS 18.2 are released before merging this one.

https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes

### CODE REVIEW

**Review by tomayac — APPROVED** [review]
LGTM, thanks for being on top of things.

**Comment by tomayac** [comment]
I let you merge this once it's released.

**Comment by dschuff** [comment]
Actually I don't see wasmgc in the release notes, have you tested on the beta?

**Comment by dschuff** [comment]
ah thanks i just missed it.

**Comment by CryZe** [comment]
This is missing the Type Reflection proposal, which is also enabled (though partially). I also had a 18.2 branch in progress where I have it like this:
```json
"typeReflection": ["18.2", "Only supports `WebAssembly.Module.imports` and `WebAssembly.Module.exports`"],
```

**Comment by chicoxyzzy** [comment]
Hmm... the value `["18.2", "Only supports WebAssembly.Module.imports and WebAssembly.Module.exports"]` seems incorrect to me. I tend to think that partial support is lack of support is more fair, so maybe it's better to keep it as `"flag"` as it is currently, and just change the version from Safari TP 202 to Safari 18.2.

**Comment by CryZe** [comment]
18.2 is out now with all those features enabled :D

**Pull request merged**
