### PR TITLE
Updated Microsoft Edge logo on home page

### PR DESCRIPTION
**Pull request by sidverma32**
### Problem
The Edge logo on the home page is the old "E" logo used by the non-Chromium based Edge.

### ChangeLog

Updated the Edge browser logo to a new one.

### CODE REVIEW

**Comment by RReverser** [comment]
> The Edge logo on the home page is the old "E" logo used by the non-Chromium based Edge.

Hm, thinking about this a bit more... the point of that row was to say that 4 major engines (including the non-Chrome Edge) has shipped WebAssembly support.

If we switch to the Chromium-based Edge logo, we might as well remove its mention altogether, because in terms of engine it's the same one as Chrome...

**Comment by sidverma32** [comment]
@RReverser Thanks for describing the problem statement. But i am little less familiar with the repo., if you can give me a heads-up on the pointer which you said  like from where to begin.

**Comment by andylizi** [comment]
This change was merged in #158, which I included as part of another project because I hadn't noticed you've already submitted this PR. I apologize for wasting your time:pensive:.

#231 can also be closed now.

**Comment by chicoxyzzy** [comment]
Fixed in #283

**Pull request closed without merging**
