### PR TITLE
Update a link to the community channel

### PR DESCRIPTION
**Pull request by hodovani**
Replace the IRC link with the Discord link.

### CODE REVIEW

**Comment by RReverser** [comment]
Oh, sorry, I just finished a Community revamp in https://github.com/WebAssembly/website/pull/219. If you don't mind, I'll let that PR supersede this one (it includes same change, among other things).

**Comment by hodovani** [comment]
@RReverser not a problem. I just wanted to update this page.

**Comment by RReverser** [comment]
Definitely appreciated, thanks!

**Comment by RReverser** [comment]
Merged the other one.

**Pull request closed without merging**
