### PR TITLE
Simplify instructions for downloading Emscripten

### PR DESCRIPTION
**Pull request by kripken**
The emsdk now has Windows binary builds, so no special process is needed there, and the old instructions for either using WSL or building from source are pretty onerous.

edit: background: WebAssembly/binaryen#2395

### CODE REVIEW

**Comment by kripken** [comment]
I'd like to land this, but am not sure what to do about CI. Perhaps #150 should land to fix it? I'm not sure who should be reviewing these things. @rreverser maybe you know?

**Comment by RReverser** [comment]
@kripken Unfortunately, no - I don't have access to the website config and not very familiar with the setup (at least yet). Maybe @lukewagner?

**Comment by kripken** [comment]
@binji perhaps you have an idea how to unblock these PRs?

**Comment by binji** [comment]
I merged #150. Let's try re-running travis to see if that fixes it.

**Comment by kripken** [comment]
Passed, thanks!

**Pull request merged**
