### PR TITLE
Update favicon with 2x resolution.

### PR DESCRIPTION
**Pull request by lgarron**
This updates the favicon to include a 2x resolution version for Retina screens.

I've also updated the 16px version to have a transparent puzzle piece indentation at the top (instead of white).

screen shot 2018-07-04 at 12 41 54

### CODE REVIEW

**Comment by adanilo** [comment]
Yes, looks great

**Comment by lgarron** [comment]
> Thanks for doing this! Are you a community group member?

You're welcome!
I'm a Chromium committer, but not officially a part of any WebAssembly effort.

**Comment by RReverser** [comment]
Can we merge this / do we need @lgarron to become a WebAssembly member first?

**Comment by adanilo** [comment]
The Jekyll build fails cause the favicons are different. Can't be merged until that's resolved.

**Comment by binji** [comment]
Being a member of the wasm community group would be preferable, yes.

**Comment by lgarron** [comment]
> Being a member of the wasm community group would be preferable, yes.

Happy to join, if that helps! What's the process?

**Comment by binji** [comment]
@lgarron thanks! You can join the group here: https://www.w3.org/community/webassembly.

**Comment by lgarron** [comment]
> @lgarron thanks! You can join the group here: https://www.w3.org/community/webassembly.

Done! Joined as `lgarron`.

**Comment by lgarron** [comment]
> The Jekyll build fails cause the favicons are different. Can't be merged until that's resolved.

What does this mean? Does it refuse to update because the favicon changed at all?

**Comment by adanilo** [comment]
If you look at the continuous integration build, it shows a red X and looking at the log it's failing when comparing the favicons. Whatever script is doing that needs to be updated before this can land - otherwise the continuous builder will fail.

**Comment by lgarron** [comment]
> Whatever script is doing that needs to be updated before this can land

Fixed!

**Comment by RReverser** [comment]
Awesome, thank you @lgarron!

**Pull request merged**
